security:
    encoders:
        App\Entity\Administrateur: { algorithm: bcrypt, cost: 4 }
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Administrateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic: ~
            anonymous: true
            form_login:
                username_parameter: email
                password_parameter: password
                check_path: app_login
                login_path: app_login
                default_target_path: app_login
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            logout:
                path: logout
                target: app_login

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ForgotPassword$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resultat, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/accueil, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/hotel, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }